CREATE TABLE [dbo].[TKCData20202021]
(
	[Id] INT NOT NULL PRIMARY KEY IDENTITY,
	[SeasonID] [int] NULL,
	[Indice] [float] NULL,
	[N°evento] [float] NULL,
	[evento] [nvarchar](255) NULL,
	[DataEV] [datetime] NULL,
	[Numerocliente] [float] NULL,
	[Intestazione] [nvarchar](255) NULL,
	[Cognome] [nvarchar](255) NULL,
	[Nome] [nvarchar](255) NULL,
	[Azienda] [nvarchar](255) NULL,
	[Via] [nvarchar](255) NULL,
	[CP] [nvarchar](255) NULL,
	[CAP] [nvarchar](255) NULL,
	[Località] [nvarchar](255) NULL,
	[StatoFederale (sigla)] [nvarchar](255) NULL,
	[NumeroDiTelefono] [nvarchar](255) NULL,
	[Cellulare] [nvarchar](255) NULL,
	[E-mail] [nvarchar](255) NULL,
	[Settore] [nvarchar](255) NULL,
	[Entrata] [nvarchar](255) NULL,
	[InfoPosti] [nvarchar](255) NULL,
	[Fila] [nvarchar](255) NULL,
	[Posto] [float] NULL,
	[CategoriaPrezzi] [nvarchar](255) NULL,
	[Riduzione] [nvarchar](255) NULL,
	[PrezzoDelBiglietto] NUMERIC(18, 2) NULL,
	[ModalitaDiSpedizione] [nvarchar](255) NULL,
	[SpeseDiSpedizione] NUMERIC(18, 2) NULL,
	[CommissioneOrdine] NUMERIC(18, 2) NULL,
	[AssicurazioneBiglietto] NUMERIC(18, 2) NULL,
	[Totale] NUMERIC(18, 2) NULL,
	[ModalitàDiPagamento] [nvarchar](255) NULL,
	[ImportoPagamento] NUMERIC(18, 2) NULL,
	[ImportoResiduo] NUMERIC(18, 2) NULL,
	[NumeroEvento] INT NULL,
	[Organizzatore] [nvarchar](255) NULL,
	[IDUtente] [float] NULL,
	[utente] [nvarchar](255) NULL,
	[NumeroOrdine] [float] NULL,
	[CommentoOrdine] [nvarchar](255) NULL,
	[Stato] [nvarchar](255) NULL,
	[DataRegistrazione] [datetime] NULL,
	[MomentoStampa] [datetime] NULL
)
